### ISSUE TITLE
Make result types no-throw move assignable and constructible

### ISSUE THREAD

**Issue by GuillaumeDua** [tgockel/zookeeper-cpp#123]
Please consider the strong exception guarantee, e.g non-throwing move-assignement/move-assignement.

Current code :

```cpp
class watch_result final
{
    watch_result(watch_result&&) = default;
    watch_result& operator=(watch_result&&) = default;
}
```

So 
```cpp
static_assert(std::is_move_assignable_v<watch_result>); // ok
static_assert(std::is_nothrow_move_assignable_v<watch_result>); // KO
```

Please consider using `noexcept` for strong exception garantee :
```cpp
watch_result& operator=(watch_result&&) noexcept = default;
```

**Comment by tgockel** [comment]
The types already have a strong exception guarantee. However, making a no-throw guarantee seems ideal here. Simply marking `watch_result`'s move-assignment operator as `noexcept` would result in a compilation error, as `get_result` is not no-throw move-assignable. The fix here is to rule-of-6 all the types.
