### ISSUE TITLE
I want to know if I can use it on Windows

### ISSUE THREAD

**Issue by 925486270** [tgockel/zookeeper-cpp#129]
I want to know if I can use it on Windows

**Comment by tgockel** [comment]
Per the [readme on non-Linux](https://github.com/tgockel/zookeeper-cpp#non-linux):

> Can you get this library working on platforms that are not Linux? Maybe. But Linux is the primary development, testing, and deployment platform of people writing distributed applications, so this library is targetted at Linux.
